### ISSUE TITLE
Replicate QGIS Hotspot Extraction Process

### ISSUE THREAD

**Issue by docligot** [Cirrolytix/aedesproject-uif#46]
Replicate the original QGIS extraction process as detailed in:

https://github.com/docligot/aedesproject/blob/master/satellite/Using%20QGIS%20to%20Extract%20Dengue%20Hotspots.pdf

**Comment by fstayco** [comment]
- [ ] 

- [ ]

**Comment by fstayco** [comment]
Closing this issue.  Refer to #64 .
